sh ./runttg.sh chi-trans-metaok baptiste1_lel french-spoken tto BOTH
sh ./runttg.sh chi-trans-metaok Cloe1_Tsc_Anon french-spoken tto BOTH
sh ./runttg.sh chi-trans-metaok gaetan1_bau french-spoken tto BOTH
sh ./runttg.sh adu-metaok communication_bon_sd french-spoken tto ADU
sh ./runttg.sh adu-metaok hallucinogenes_cag_03 french-spoken tto ADU
sh ./runttg.sh adu-metaok lecturecroco_sd french-spoken tto ADU
sh ./runttg.sh adu-metaok pompe_bli_sd french-spoken tto ADU
sh ./runttg.sh adu-metaok sculpture_sd french-spoken tto ADU
sh ./runttg.sh adu-metaok tatouagepolynesie_06 french-spoken tto ADU
sh ./runttg.sh adu-metaok theorielinguistique_07 french-spoken tto ADU
sh ./runttg.sh adu-metaok vampiretatouage_sd french-spoken tto ADU
